# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PanoramaViewer3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(522, 760)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 40))
        self.groupBox.setMaximumSize(QtCore.QSize(10000, 40))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_input = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_input.sizePolicy().hasHeightForWidth())
        self.btn_input.setSizePolicy(sizePolicy)
        self.btn_input.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_input.setMaximumSize(QtCore.QSize(80, 25))
        self.btn_input.setObjectName("btn_input")
        self.horizontalLayout.addWidget(self.btn_input)
        self.btn_export = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_export.sizePolicy().hasHeightForWidth())
        self.btn_export.setSizePolicy(sizePolicy)
        self.btn_export.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_export.setMaximumSize(QtCore.QSize(80, 25))
        self.btn_export.setObjectName("btn_export")
        self.horizontalLayout.addWidget(self.btn_export)
        self.btn_stitch = QtWidgets.QPushButton(self.groupBox)
        self.btn_stitch.setMinimumSize(QtCore.QSize(80, 25))
        self.btn_stitch.setMaximumSize(QtCore.QSize(80, 25))
        self.btn_stitch.setObjectName("btn_stitch")
        self.horizontalLayout.addWidget(self.btn_stitch)
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_original = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_original.sizePolicy().hasHeightForWidth())
        self.label_original.setSizePolicy(sizePolicy)
        self.label_original.setObjectName("label_original")
        self.verticalLayout_2.addWidget(self.label_original)
        self.img_input = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_input.sizePolicy().hasHeightForWidth())
        self.img_input.setSizePolicy(sizePolicy)
        self.img_input.setMaximumSize(QtCore.QSize(500, 250))
        self.img_input.setAutoFillBackground(False)
        self.img_input.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.img_input.setText("")
        self.img_input.setScaledContents(True)
        self.img_input.setObjectName("img_input")
        self.verticalLayout_2.addWidget(self.img_input)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.openGLWidget.setObjectName("openGLWidget")
        self.horizontalLayout_2.addWidget(self.openGLWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox_rotation = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_rotation.sizePolicy().hasHeightForWidth())
        self.groupBox_rotation.setSizePolicy(sizePolicy)
        self.groupBox_rotation.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_rotation.setObjectName("groupBox_rotation")
        self.rotationSlider_L = QtWidgets.QSlider(self.groupBox_rotation)
        self.rotationSlider_L.setGeometry(QtCore.QRect(0, 20, 121, 21))
        self.rotationSlider_L.setMinimum(-90)
        self.rotationSlider_L.setMaximum(90)
        self.rotationSlider_L.setOrientation(QtCore.Qt.Horizontal)
        self.rotationSlider_L.setObjectName("rotationSlider_L")
        self.rotationSlider_R = QtWidgets.QSlider(self.groupBox_rotation)
        self.rotationSlider_R.setGeometry(QtCore.QRect(205, 20, 121, 22))
        self.rotationSlider_R.setMinimum(-90)
        self.rotationSlider_R.setMaximum(90)
        self.rotationSlider_R.setSingleStep(1)
        self.rotationSlider_R.setOrientation(QtCore.Qt.Horizontal)
        self.rotationSlider_R.setObjectName("rotationSlider_R")
        self.label_rotation_L = QtWidgets.QLabel(self.groupBox_rotation)
        self.label_rotation_L.setGeometry(QtCore.QRect(130, 20, 47, 13))
        self.label_rotation_L.setObjectName("label_rotation_L")
        self.label_rotation_R = QtWidgets.QLabel(self.groupBox_rotation)
        self.label_rotation_R.setGeometry(QtCore.QRect(335, 20, 47, 13))
        self.label_rotation_R.setObjectName("label_rotation_R")
        self.resetRotation = QtWidgets.QPushButton(self.groupBox_rotation)
        self.resetRotation.setGeometry(QtCore.QRect(400, 20, 75, 23))
        self.resetRotation.setObjectName("resetRotation")
        self.verticalLayout.addWidget(self.groupBox_rotation)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(192222, 50))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.fov_slider = QtWidgets.QSlider(self.groupBox_2)
        self.fov_slider.setGeometry(QtCore.QRect(0, 10, 121, 22))
        self.fov_slider.setToolTipDuration(2)
        self.fov_slider.setMinimum(180)
        self.fov_slider.setMaximum(210)
        self.fov_slider.setProperty("value", 195)
        self.fov_slider.setOrientation(QtCore.Qt.Horizontal)
        self.fov_slider.setObjectName("fov_slider")
        self.fov_label = QtWidgets.QLabel(self.groupBox_2)
        self.fov_label.setGeometry(QtCore.QRect(130, 10, 61, 21))
        self.fov_label.setObjectName("fov_label")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(200, 10, 91, 17))
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_input.setText(_translate("MainWindow", "Choose Image"))
        self.btn_export.setText(_translate("MainWindow", "Export"))
        self.btn_stitch.setText(_translate("MainWindow", "Stitch"))
        self.label_original.setText(_translate("MainWindow", "Input Image"))
        self.groupBox_rotation.setTitle(_translate("MainWindow", "Rotation"))
        self.label_rotation_L.setText(_translate("MainWindow", "angle:"))
        self.label_rotation_R.setText(_translate("MainWindow", "angle: "))
        self.resetRotation.setText(_translate("MainWindow", "reset"))
        self.fov_label.setText(_translate("MainWindow", "fov: "))
        self.radioButton.setText(_translate("MainWindow", "show grid line"))

